name: First WorkFlow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "Log from step one"
      - name: Step Two
        run: echo "Log from step two"
