name: First WorkFlow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "Log from step one"
      - name: Step Two
        run: echo "Log from step two"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Cowsays
      # You may pin to the exact commit or the version.
      # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
      uses: mscoutermarsh/cowsays-action@v1
      with:
        # What does the cow say?
        text: "Ready for Prod --  Ship it!!!!!"
        # Color of your cow
        color: "red"
                
          
